// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3q6EedFmBhGqjLTe8D-sfKhHtn1Gmv-o',
    appId: '1:738675864589:web:5a1a2afbbdd5cce99a5144',
    messagingSenderId: '738675864589',
    databaseURL: 'https://fir-f8fc2-default-rtdb.firebaseio.com/',
    projectId: 'fir-f8fc2',
    authDomain: 'fir-f8fc2.firebaseapp.com',
    storageBucket: 'fir-f8fc2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9oBo1nZ7joosKLI7yUiT0SwMWU8r0q0w',
    appId: '1:738675864589:android:d9990873ca9077109a5144',
    messagingSenderId: '738675864589',
    projectId: 'fir-f8fc2',
    storageBucket: 'fir-f8fc2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXMV6sGyghTFqf8f3LzpJYoyz68MV555g',
    appId: '1:738675864589:ios:301f48a5cb9e62f59a5144',
    messagingSenderId: '738675864589',
    projectId: 'fir-f8fc2',
    storageBucket: 'fir-f8fc2.appspot.com',
    iosClientId:
        '738675864589-k2efn1j4gkf30l54c1pmt85kbmhfc3d9.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXMV6sGyghTFqf8f3LzpJYoyz68MV555g',
    appId: '1:738675864589:ios:301f48a5cb9e62f59a5144',
    databaseURL: 'https://fir-f8fc2-default-rtdb.firebaseio.com/',
    messagingSenderId: '738675864589',
    projectId: 'fir-f8fc2',
    storageBucket: 'fir-f8fc2.appspot.com',
    iosClientId:
        '738675864589-k2efn1j4gkf30l54c1pmt85kbmhfc3d9.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );
}
