// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAjnPBN6WYsJVxxm4iy8MzPUacyBMjHa8',
    appId: '1:499905847788:web:88b53eece3b246ac8320c9',
    messagingSenderId: '499905847788',
    projectId: 'themightiest-2fa27',
    authDomain: 'themightiest-2fa27.firebaseapp.com',
    storageBucket: 'themightiest-2fa27.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaz0pGm_crwdbPsxq9YPH8eCKq23W_B-0',
    appId: '1:499905847788:android:58d5a06900d18ba58320c9',
    messagingSenderId: '499905847788',
    projectId: 'themightiest-2fa27',
    storageBucket: 'themightiest-2fa27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkjp3rRLF02uWt_VItL8JugcnpMQFE74Y',
    appId: '1:499905847788:ios:e5dc0bc3fdf44e7a8320c9',
    messagingSenderId: '499905847788',
    projectId: 'themightiest-2fa27',
    storageBucket: 'themightiest-2fa27.appspot.com',
    iosClientId: '499905847788-n673nnoj65edgondvli420olrtitvj3e.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkjp3rRLF02uWt_VItL8JugcnpMQFE74Y',
    appId: '1:499905847788:ios:e5dc0bc3fdf44e7a8320c9',
    messagingSenderId: '499905847788',
    projectId: 'themightiest-2fa27',
    storageBucket: 'themightiest-2fa27.appspot.com',
    iosClientId: '499905847788-n673nnoj65edgondvli420olrtitvj3e.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );
}
